name: "set-matrix action"
description: "Create a matrix of changes"
author: aorfanos
runs:
  using: "composite"
  steps:
    - id: set-matrix
      run: python ${{ github.action_path }}/set-matrix.py
      shell: bash
outputs:
  matrix:
    description: "Changes matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}
